services:
  live-msg-provider-docker-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'live-msg-provider-docker:latest'
    environment:
      - spring.cloud.nacos.discovery.ip=${DEV_HOST} # 不同物理机必须明确指定IP
      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
      - DUBBO_PORT_TO_BIND=29951            # 容器内 Dubbo 服务绑定的端口（会覆盖 dubbo.protocol.port）
      - NACOS_HOST=${DEV_HOST}
      - MYSQL_HOST=${DEV_HOST}
      - ROCKETMQ_HOST=${DEV_HOST}
      - REDIS_HOST=${DEV_HOST}
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
    ports:
      - '29951:29951'
    volumes:
      - D:\tmp\logs\live-msg-provider-1:/tmp/logs/live-msg-provider
  
#  live-msg-provider-docker-2:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    image: 'live-msg-provider-docker:latest'
#    environment:
#      - spring.cloud.nacos.discovery.ip=${DEV_HOST} # 不同物理机必须明确指定IP
#      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
#      - DUBBO_PORT_TO_BIND=29952
#      - NACOS_HOST=${DEV_HOST}
#      - MYSQL_HOST=${DEV_HOST}
#      - ROCKETMQ_HOST=${DEV_HOST}
#      - REDIS_HOST=${DEV_HOST}
#      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
#    ports:
#      - '29952:29952'
#    volumes:
#      - D:\tmp\logs\live-msg-provider-2:/tmp/logs/live-msg-provider