config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:8848
    
server:
  port: 8700
  
spring:
  application:
    name: live-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: live-test
      config:
        file-extension: yaml
        server-addr: ${config.nacos.host}
        namespace: live-test
        group: DEFAULT_GROUP
  config:
    import: 
      - optional:nacos:live-gateway-config.yaml
    