config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    username: nacos
    password: nacos
  rocketmq:
    host: ${ROCKETMQ_HOST}:9876
    
spring:
  cloud:
    nacos:
      username: ${config.nacos.username}
      password: ${config.nacos.password}
      discovery:
        server-addr: ${config.nacos.host}
        namespace: public
    stream:
      function:
        definition: imBizMsg
      bindings:
        imBizMsg-in-0:
          destination: live-im-biz-msg-topic
          group: im-biz-msg-group
          content-type: application/json
      rocketmq:
        binder:
          name-server: ${config.rocketmq.host}
          enable-msg-trace: true

dubbo:
  protocol:
    name: dubbo
    port: 29971
  application:
    name: dubbo-live-im-router-provider
    qos-enable: false
  registry:
    address: nacos://${config.nacos.host}?namespace=public&username=${config.nacos.username}&password=${config.nacos.password}
  consumer:
    cluster: imRouter
