services:
  live-api-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'live-api:latest'
    environment:
      - server.port=9901
      - spring.cloud.nacos.discovery.ip=${DEV_HOST} # 不同物理机必须明确指定IP
      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
      - NACOS_HOST=${DEV_HOST}
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
    ports:
      - '9901:9901'
    volumes:
      - D:\tmp\logs\live-api-1:/tmp/logs/live-api
    
#  live-api-2:
#    image: 'live-api:latest'
#    environment:
#      - server.port=9902
#      - spring.cloud.nacos.discovery.ip=${DEV_HOST}
#      - DUBBO_IP_TO_REGISTRY=${DEV_HOST}
#      - NACOS_HOST=${DEV_HOST}
#      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
#    ports:
#      - '9902:9902'
#    volumes:
#      - D:\tmp\logs\live-api-2:/tmp/logs/live-api
