#config:
#  nacos:
#    host: ${NACOS_HOST:127.0.0.1}:18848
#  rocketmq:
#    host: ${ROCKETMQ_HOST:192.168.0.100}:9876
#
#im:
#  bind:
#    server:
#      ip: 192.168.0.100 # 用户登录后保存用户和所在服务器的关系，用于转发消息时确定接收方的节点，不能在代码里获取LocalHost，因为部署在容器里获取不到真实ip
#  ws:
#    web-socket-ip: live.aiolos.com  # 接收im消息发服务ip或可解析域名
#    port: 19990   # im服务端监听的端口
#  tcp:
#    port: 19991
#
#spring:
#  cloud:
#    stream:
#      function:
#        definition: imBizMsg;imAckDelayMsg;imOnlineMsg;imOfflineMsg
#      bindings:
#        imBizMsg-out-0:
#          destination: live-im-biz-msg-topic
#          content-type: application/json
#        imAckDelayMsg-out-0:
#          destination: live-im-ack-delay-msg-topic
#          content-type: application/json
#        imOnlineMsg-out-0:
#          destination: live-im-online-msg-topic
#          content-type: application/json
#        imOfflineMsg-out-0:
#          destination: live-im-offline-msg-topic
#          content-type: application/json
#        imAckDelayMsg-in-0:
#          destination: live-im-ack-delay-msg-topic
#          group: im-ack-delay-msg-group
#          content-type: application/json
#      rocketmq:
#        binder:
#          name-server: ${config.rocketmq.host}
#          enable-msg-trace: true
#  data:
#    redis:
#      port: 6379
#      host: ${REDIS_HOST:127.0.0.1}
#      database: 0
#      lettuce:
#        pool:
#          min-idle: 10
#          max-idle: 20
#          max-active: 50
#
#dubbo:
#  protocol:
#    name: dubbo
#    port: 29961
#  application:
#    name: dubbo-live-im-core-server
#    qos-enable: false
#  registry:
#    address: nacos://${config.nacos.host}?namespace=live-test&username=nacos&password=nacos