#spring:
#  cloud:
#    stream:
#      function:
#        # 多个函数必须要配置function.definition，函数名用 ; 隔开
#        definition: imBizMsg
#      bindings:
#        imBizMsg-in-0:
#          destination: live-im-biz-msg-topic
#          group: im-biz-msg-group
#          content-type: application/json
#      rocketmq:
#        binder:
#          name-server: ${ROCKETMQ_HOST:192.168.0.100}:9876
#          enable-msg-trace: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/live?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#  data:
#    redis:
#      port: 6379
#      host: ${REDIS_HOST:127.0.0.1}
#      database: 0
#      lettuce:
#        pool:
#          min-idle: 0
#          max-idle: 8
#          max-active: 8
#
#dubbo:
#  protocol:
#    name: dubbo
#    port: 20882
#  application:
#    name: dubbo-live-msg-provider
#    qos-enable: false
#  registry:
#    address: nacos://${NACOS_HOST:127.0.0.1}:18848?namespace=live-test&username=nacos&password=nacos
#  consumer:
#    check: false