#config:
#  service:
#    id: 1001  # 服务器唯一标识
#  nacos:
#    host: ${NACOS_HOST:127.0.0.1}:18848
#
#spring:
#  data:
#    redis:
#      port: 6379
#      host: ${REDIS_HOST:127.0.0.1}
#      database: 0
#      lettuce:
#        pool:
#          min-idle: 10
#          max-idle: 20
#          max-active: 50
#
#dubbo:
#  protocol:
#    name: dubbo
#    port: 29931
#  application:
#    name: dubbo-live-account-provider
#    qos-enable: false
#  registry:
#    address: nacos://${config.nacos.host}?namespace=live-test&username=nacos&password=nacos