config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
  rocketmq:
    host: ${ROCKETMQ_HOST:127.0.0.1}:9876

spring:
  application:
    name: live-living-provider
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: live-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/live?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:127.0.0.1}
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

dubbo:
  protocol:
    name: dubbo
    port: 22882
  application:
    name: dubbo-live-living-provider
    qos-enable: false
  registry:
    address: nacos://${config.nacos.host}?namespace=live-test&username=nacos&password=nacos
  consumer:
    check: false