config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
  rocketmq:
    host: ${ROCKETMQ_HOST:127.0.0.1}:9876

spring:
  application:
    name: live-living-provider
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: live-test
    stream:
      function:
        definition: imOnlineMsg;imOfflineMsg
      bindings:
        imOnlineMsg-in-0:
          destination: live-im-online-msg-topic
          group: im-online-msg-group
          content-type: application/json
        imOfflineMsg-in-0:
          destination: live-im-offline-msg-topic
          group: im-offline-msg-group
          content-type: application/json
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_HOST:192.168.0.100}:9876
          enable-msg-trace: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/live?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:127.0.0.1}
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

dubbo:
  protocol:
    name: dubbo
    port: 22882
  application:
    name: dubbo-live-living-provider
    qos-enable: false
  registry:
    address: nacos://${config.nacos.host}?namespace=live-test&username=nacos&password=nacos
  consumer:
    check: false
    
task:
  refresh-living-room:
    ip: 192.168.0.100