config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848

spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: dev
      config:
        file-extension: yaml
        server-addr: ${config.nacos.host}
        namespace: dev
        group: DEFAULT_GROUP
  config:
    import:
      - optional:nacos:live-living-provider-config.yaml