services:
  live-user-provider-docker-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'live-user-provider-docker:latest'
    environment:
      - server.port=8781
      - spring.cloud.nacos.discovery.ip=192.168.0.101 # 不同物理机必须明确指定IP
      - DUBBO_IP_TO_REGISTRY=192.168.0.101
      - DUBBO_PORT_TO_BIND=20880            # 容器内 Dubbo 服务绑定的端口（需与 dubbo.protocol.port 一致）
      - NACOS_HOST=192.168.0.101
      - REDIS_HOST=192.168.0.101
      - ROCKETMQ_HOST=192.168.0.101
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
    ports:
      - '8781:8781'
      - '20880:20880'
    extra_hosts:
      - 'master.mysql.com:192.168.0.101'
      - 'slave.mysql.com:192.168.0.101'
    volumes:
      - D:\tmp\logs\live-user-provider-1:/tmp/logs/live-user-provider
    
  live-user-provider-docker-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 'live-user-provider-docker:latest'
    environment:
      - server.port=8782
      - spring.cloud.nacos.discovery.ip=192.168.0.101
      - DUBBO_IP_TO_REGISTRY=192.168.0.101
      - DUBBO_PORT_TO_BIND=20881
      - NACOS_HOST=192.168.0.101
      - REDIS_HOST=192.168.0.101
      - ROCKETMQ_HOST=192.168.0.101
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms256m -Xmx256m -Xmn128m -Xss256k
    ports:
      - '8782:8782'
      - '20881:20881'
    extra_hosts:
      - 'master.mysql.com:192.168.0.101'
      - 'slave.mysql.com:192.168.0.101'
    volumes:
      - D:\tmp\logs\live-user-provider-2:/tmp/logs/live-user-provider
